docker image

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -7,7 +7,7 @@ on:
       - "main"
       - "master"
   schedule:
-    - cron: '0 5 * * 0'
+    - cron: '0 5 * * *'
   pull_request:
     branches: ["**"]
 
@@ -16,25 +16,43 @@ env:
   REGISTRY: docker.io
   # Image repository, without hostname and tag
   IMAGE_NAME: alpine/helm
+  REPO_NAME: helm/helm
+  REBUILD: false
   SHA: ${{ github.event.pull_request.head.sha || github.event.after }}
 
 jobs:
-  build:
+  check_tag:
     runs-on: ubuntu-latest
     permissions:
       pull-requests: write
 
     steps:
-      - name: Setup Docker buildx
-        uses: docker/setup-buildx-action@v3
-
       # Step to fetch the latest version
       - name: Get latest version
         id: curl-version
         run: |
-           VERSION=$(curl -s https://api.github.com/repos/helm/helm/releases | jq -r '.[].tag_name | select(test("alpha|beta|rc") | not) ' | sort -rV | head -n 1 |sed 's/v//')
-           echo "Latest helm version is $VERSION"
+           VERSION=$(curl -s https://api.github.com/repos/${REPO_NAME}/releases | jq -r '.[].tag_name | select(test("alpha|beta|rc") | not) ' | sort -rV | head -n 1 |sed 's/v//')
+           echo "Latest version is $VERSION"
            echo "VERSION=$VERSION" >> $GITHUB_ENV
+           status=$(curl -sL https://hub.docker.com/v2/repositories/${IMAGE_NAME}/tags/${VERSION})
+           echo $status
+           if [[ ( "${status}" =~ "not found" ) ||( ${REBUILD} == "true" ) ]]; then
+             echo "build image for ${VERSION}"
+             echo "build_required=true" >> $GITHUB_OUTPUT
+           else
+             echo "Tag ${VERSION} is exist, skip"
+             echo "build_required=false" >> $GITHUB_OUTPUT
+           fi
+
+  build_and_push:
+    runs-on: ubuntu-latest
+    needs: check_tag
+    if: needs.check_tag.outputs.build_required == 'true'
+    permissions:
+      pull-requests: write
+    steps:
+      - name: Setup Docker buildx
+        uses: docker/setup-buildx-action@v3
 
       # Authenticate to the container registry
       - name: Authenticate to registry ${{ env.REGISTRY }}
